Repository hassio-addons/addon-ftp, pull requests merged in 2021-04, with the labels that each got.

#46 Make add-on icons transparent
  ftp/icon.png
  ftp/logo.png
Labels: documentation

#52 Upgrades add-on base image to v9.2.0
  ftp/Dockerfile
  ftp/build.json
Labels: dependencies

#53 Apply updated repository structure & CI workflow
  .editorconfig
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/pr-labels.yaml
Labels: ci
