Repository hassio-addons/addon-ftp, pull requests merged in 2021-11, with the labels that each got.

#100 Switch to centralized GitHub Action Workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#101 Migrate JSON config to YAML
  ftp/build.json
  ftp/build.yaml
  ftp/config.json
  ftp/config.yaml
Labels: refactor

#102 ⬆️ Upgrades add-on base image to 10.2.0
  ftp/Dockerfile
  ftp/build.yaml
Labels: dependencies

#103 ⬆️ Upgrades add-on base image to 10.2.2
  ftp/Dockerfile
  ftp/build.yaml
Labels: dependencies

#105 ⬆️ Upgrades add-on base image to 11.0.0
  ftp/Dockerfile
  ftp/build.yaml
Labels: minor, dependencies

#106 Allow for showing hidden dot files
  ftp/rootfs/etc/vsftpd/vsftpd.conf
Labels: new-feature

#107 Fix SSL no ciphers available
  ftp/rootfs/etc/vsftpd/vsftpd.conf
Labels: bugfix

#56 Use rbind for mounting the folders so it will include all subfolders
  ftp/rootfs/etc/cont-init.d/users.sh
Labels: bugfix
